Feature/doubleroom
VVervolk/15-team-project pull request #18
Opened 2023-01-31 12:27 UTC by Marlen13

Оформление кнопок пока не делала, жду до вечера собрания -решения что делаем.
Кнопка с посиланням какой указывать href. Видимо как обновлю main - будет видно.
Переменные тоже не все у меня были - добавляла свои
Работаю над слайдером.

2023-01-31 13:38 UTC, VVervolk requested changes
Остальное в Slack

2023-01-31 13:38 UTC, VVervolk commented on src/partials/sections/section-roomluxe.html
> +                <p class="room-logo">Mimino</p>
Нужно Mimiho

2023-01-31 13:38 UTC, VVervolk commented on src/sass/layout/_roomluxe.scss
> +    font-family: Georgia, 'Times New Roman', Times, serif;
Зачем Georgia?

2023-01-31 13:41 UTC, Marlen13 commented on src/sass/layout/_roomluxe.scss
> +    font-family: Georgia, 'Times New Roman', Times, serif;
При выборе 'Times New Roman' подключилась вся выборка - сама удивилась

2023-01-31 13:57 UTC, Marlen13 commented on src/sass/layout/_roomluxe.scss
> +    font-family: Georgia, 'Times New Roman', Times, serif;
Оставлю только 'Times New Roman'

2023-02-01 15:45 UTC, VVervolk requested changes
Фото должны быть зафиксированные 
https://www.loom.com/share/e269c8db42d74561a055dd31bbc8daf5

2023-02-02 16:50 UTC, GumeniukRuslan requested changes
у вас ниже 414пх картинка картинка с классом room-main меняется на большую версию, насколько я понимаю это потому что в src указана именно большая версия с пометкой l1 а вам нужно указать ту которая с s1, тоже самое в слайдере.
и второе, кнопки "детальніше" и "переглянути ціни" должны быть одинаковы по ширине

2023-02-03 07:52 UTC, GumeniukRuslan approved these changes
все гуд

2023-02-03 11:01 UTC, merged